# Generated by Django 2.2.5 on 2020-07-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='My Awesome Blog', max_length=30),
        ),
    ]
